all: main.c
	gcc -o main main.c
launch:
	./main
setup:
	curl -L https://github.com/DaveGamble/cJSON/raw/master/cJSON.h -o cJSON.h
	curl -L https://github.com/DaveGamble/cJSON/raw/master/cJSON.c -o cJSON.c