// Generated by CoffeeScript 2.7.0
(function() {
  var fs, i, j, len, len1, parsedSpawns, path, ref, scene, spawn, spawns;

  fs = require('fs');

  path = require('path');

  spawns = JSON.parse(fs.readFileSync(path.join(__dirname, '../../data/spawns.json')));

  parsedSpawns = {};

  for (i = 0, len = spawns.length; i < len; i++) {
    scene = spawns[i];
    ref = scene.spawns;
    for (j = 0, len1 = ref.length; j < len1; j++) {
      spawn = ref[j];
      parsedSpawns[spawn.monsterId] = parsedSpawns[spawn.monsterId] || [];
      parsedSpawns[spawn.monsterId].push([spawn.pos.x, spawn.pos.y, spawn.pos.z]);
    }
  }

  fs.writeFileSync(path.join(__dirname, '../../parsed/parsedSpawns.json'), JSON.stringify(parsedSpawns, null, 4));

}).call(this);
